[FIX] base: prevent error on encoding declaration in xml editor
Currently, an error occurs when a user includes an XML encoding declaration in
the studio XML editor.

Steps to produce:

- Install the web_studio module and enable developer mode
- Open Apps > studio > view > '</> xml'
- Declare encoding as: <?xml version='1.0' encoding='utf-8'?> and click save

Error:
ValueError: Unicode strings with encoding declaration are not supported.
Please use bytes input or XML fragments without declaration.

Root cause:
At [1], an error is raised when the XML declaration contains an encoding
attribute, as encoding declarations are invalid in Unicode strings.

Fix:
This commit ensures that a UserError is raised, improving the error message
clarity.

A similar fix was applied in [2].

[1]:
https://github.com/odoo/odoo/blob/8a22b6ca09e1da3ccba3540bc4851a5174e035cc/odoo/tools/translate.py#L316

[2]:
https://github.com/odoo/odoo/pull/205324

sentry-6981234548

closes odoo/odoo#239743

X-original-commit: 41d503e530e8a9015b8c074f95f2644fed8ac784
Signed-off-by: Rémy Voet (ryv) <ryv@odoo.com>
Signed-off-by: Utsav Maru (utma) <utma@odoo.com>